version: '3.7'
services:
  web:
    image: python
    container_name: tb_app
    build: .
    volumes:
      - .:/home
    expose:
      - "5000"
      - "8000"
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: test
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      DEBUG: 'true'
    networks: 
      - mynetwork

  db:
    image: postgres
    networks: 
      - mynetwork
  
networks: 
  mynetwork: